package com.example.mylibrary.atoms.icons

import com.example.mylibrary.R
import com.example.mylibrary.tokens.base.IconToken

data class LibraryPeopleIconsTokens(

    //PEOPLE ICONS (62)
    val accessibleMenu: IconToken,
    val accessibility: IconToken,
    val accessibilityNew: IconToken,
    val accessible: IconToken,
    val accessibleForward: IconToken,
    val accountChildInvert: IconToken,
    val accountCircle: IconToken,
    val accountCircleOff: IconToken,
    val artist: IconToken,
    val assistWalker: IconToken,
    val babyChangingStation: IconToken,
    val blind: IconToken,
    val bodySystem: IconToken,
    val boy: IconToken,
    val coPresent: IconToken,
    val communication: IconToken,
    val conditions: IconToken,
    val directionsRun: IconToken,
    val directionsWalk: IconToken,
    val diversity1: IconToken,
    val diversity2: IconToken,
    val diversity3: IconToken,
    val elderly: IconToken,
    val elderlyWoman: IconToken,
    val emojiPeople: IconToken,
    val falling: IconToken,
    val familyRestroom: IconToken,
    val followTheSigns: IconToken,
    val group: IconToken,
    val groupAdd: IconToken,
    val groupAuto: IconToken,
    val groupRemove: IconToken,
    val groupSearch: IconToken,
    val guardian: IconToken,
    val hail: IconToken,
    val hiking: IconToken,
    val howToReg: IconToken,
    val man: IconToken,
    val man4: IconToken,
    val manageAccounts: IconToken,
    val notAccessible: IconToken,
    val passkey: IconToken,
    val person: IconToken,
    val personAdd: IconToken,
    val personAlert: IconToken,
    val personCancel: IconToken,
    val personCelebrate: IconToken,
    val personEdit: IconToken,
    val personHeart: IconToken,
    val personInjury: IconToken,
    val personOff: IconToken,
    val personRemove: IconToken,
    val personSearch: IconToken,
    val personShield: IconToken,
    val productivity: IconToken,
    val recentPatient: IconToken,
    val reduceCapacity: IconToken,
    val safetyDivider: IconToken,
    val supervisedUserCircle: IconToken,
    val supervisorAccount: IconToken,
    val transferWithinAStation: IconToken,
    val wc: IconToken,

    ){
    companion object{
        val people = LibraryPeopleIconsTokens(
            //PEOPLE ICONS (62)
            accessibleMenu = IconToken("ic_accessible_menu", R.drawable.ic_accessible_menu),
            accessibility = IconToken("ic_accessibility", R.drawable.ic_accessibility),
            accessibilityNew = IconToken("ic_accessibility_new", R.drawable.ic_accessibility_new),
            accessible = IconToken("ic_accessible", R.drawable.ic_accessible),
            accessibleForward = IconToken("ic_accessible_forward", R.drawable.ic_accessible_forward),
            accountChildInvert = IconToken("ic_account_child_invert", R.drawable.ic_account_child_invert),
            accountCircle = IconToken("ic_account_circle", R.drawable.ic_account_circle),
            accountCircleOff = IconToken("ic_account_circle_off", R.drawable.ic_account_circle_off),
            artist = IconToken("ic_artist", R.drawable.ic_artist),
            assistWalker = IconToken("ic_assist_walker", R.drawable.ic_assist_walker),
            babyChangingStation = IconToken("ic_baby_changing_station", R.drawable.ic_baby_changing_station),
            blind = IconToken("ic_blind", R.drawable.ic_blind),
            bodySystem = IconToken("ic_body_system", R.drawable.ic_body_system),
            boy = IconToken("ic_boy", R.drawable.ic_boy),
            coPresent = IconToken("ic_co_present", R.drawable.ic_co_present),
            communication = IconToken("ic_communication", R.drawable.ic_communication),
            conditions = IconToken("ic_conditions", R.drawable.ic_conditions),
            directionsRun = IconToken("ic_directions_run", R.drawable.ic_directions_run),
            directionsWalk = IconToken("ic_directions_walk", R.drawable.ic_directions_walk),
            diversity1 = IconToken("ic_diversity_1", R.drawable.ic_diversity_1),
            diversity2 = IconToken("ic_diversity_2", R.drawable.ic_diversity_2),
            diversity3 = IconToken("ic_diversity_3", R.drawable.ic_diversity_3),
            elderly = IconToken("ic_elderly", R.drawable.ic_elderly),
            elderlyWoman = IconToken("ic_elderly_woman", R.drawable.ic_elderly_woman),
            emojiPeople = IconToken("ic_emoji_people", R.drawable.ic_emoji_people),
            falling = IconToken("ic_falling", R.drawable.ic_falling),
            familyRestroom = IconToken("ic_family_restroom", R.drawable.ic_family_restroom),
            followTheSigns = IconToken("ic_follow_the_signs", R.drawable.ic_follow_the_signs),
            group = IconToken("ic_group", R.drawable.ic_group),
            groupAdd = IconToken("ic_group_add", R.drawable.ic_group_add),
            groupAuto = IconToken("ic_group_auto", R.drawable.ic_group_auto),
            groupRemove = IconToken("ic_group_remove", R.drawable.ic_group_remove),
            groupSearch = IconToken("ic_group_search", R.drawable.ic_group_search),
            guardian = IconToken("ic_guardian", R.drawable.ic_guardian),
            hail = IconToken("ic_hail", R.drawable.ic_hail),
            hiking = IconToken("ic_hiking", R.drawable.ic_hiking),
            howToReg = IconToken("ic_how_to_reg", R.drawable.ic_how_to_reg),
            man = IconToken("ic_man", R.drawable.ic_man),
            man4 = IconToken("ic_man_4", R.drawable.ic_man_4),
            manageAccounts = IconToken("ic_manage_accounts", R.drawable.ic_manage_accounts),
            notAccessible = IconToken("ic_not_accessible", R.drawable.ic_not_accessible),
            passkey = IconToken("ic_passkey", R.drawable.ic_passkey),
            person = IconToken("ic_person", R.drawable.ic_person),
            personAdd = IconToken("ic_person_add", R.drawable.ic_person_add),
            personAlert = IconToken("ic_person_alert", R.drawable.ic_person_alert),
            personCancel = IconToken("ic_person_cancel", R.drawable.ic_person_cancel),
            personCelebrate = IconToken("ic_person_celebrate", R.drawable.ic_person_celebrate),
            personEdit = IconToken("ic_person_edit", R.drawable.ic_person_edit),
            personHeart = IconToken("ic_person_heart", R.drawable.ic_person_heart),
            personInjury = IconToken("ic_person_injury", R.drawable.ic_person_injury),
            personOff = IconToken("ic_person_off", R.drawable.ic_person_off),
            personRemove = IconToken("ic_person_remove", R.drawable.ic_person_remove),
            personSearch = IconToken("ic_person_search", R.drawable.ic_person_search),
            personShield = IconToken("ic_person_shield", R.drawable.ic_person_shield),
            productivity = IconToken("ic_productivity", R.drawable.ic_productivity),
            recentPatient = IconToken("ic_recent_patient", R.drawable.ic_recent_patient),
            reduceCapacity = IconToken("ic_reduce_capacity", R.drawable.ic_reduce_capacity),
            safetyDivider = IconToken("ic_safety_divider", R.drawable.ic_safety_divider),
            supervisedUserCircle = IconToken("ic_supervised_user_circle", R.drawable.ic_supervised_user_circle),
            supervisorAccount = IconToken("ic_supervisor_account", R.drawable.ic_supervisor_account),
            transferWithinAStation = IconToken("ic_transfer_within_a_station", R.drawable.ic_transfer_within_a_station),
            wc = IconToken("ic_wc", R.drawable.ic_wc),
        )
    }
}