package cruxui.android.maracuya.atoms.icons

import cruxui.android.maracuya.R
import cruxui.android.maracuya.tokens.base.IconToken

data class LibraryMoneyIconsTokens (
    //MONEY ICONS (44)
    val accountBalanceWallet: IconToken,
    val addCard: IconToken,
    val addShoppingCart: IconToken,
    val bitcoin: IconToken,
    val cardMembership: IconToken,
    val cardTravel: IconToken,
    val colon: IconToken,
    val creditCard: IconToken,
    val creditCardClock: IconToken,
    val creditCardGear: IconToken,
    val creditCardHeart: IconToken,
    val creditCardOff: IconToken,
    val creditScore: IconToken,
    val dollar: IconToken,
    val dollarCircle: IconToken,
    val dollarExchange: IconToken,
    val dollarOff: IconToken,
    val euro: IconToken,
    val franc: IconToken,
    val lira: IconToken,
    val moneyBag: IconToken,
    val moneyRange: IconToken,
    val paymentArrowDown: IconToken,
    val paymentCard: IconToken,
    val payments: IconToken,
    val pound: IconToken,
    val productionQuantityLimits: IconToken,
    val psychiatry: IconToken,
    val redeem: IconToken,
    val ruble: IconToken,
    val rupee: IconToken,
    val savings: IconToken,
    val sendMoney: IconToken,
    val shoppingBag: IconToken,
    val shoppingBagSpeed: IconToken,
    val shoppingCart: IconToken,
    val shoppingCartCheckout: IconToken,
    val shoppingCartOff: IconToken,
    val sprint: IconToken,
    val toll: IconToken,
    val universalCurrency: IconToken,
    val universalCurrencyAlt: IconToken,
    val wallet: IconToken,
    val yen: IconToken

){
    companion object{
        val money = LibraryMoneyIconsTokens(
            //MONEY ICONS (44)

            accountBalanceWallet = IconToken("ic_account_balance_wallet", R.drawable.ic_account_balance_wallet),
            addCard = IconToken("ic_add_card", R.drawable.ic_add_card),
            addShoppingCart = IconToken("ic_add_shopping_cart", R.drawable.ic_add_shopping_cart),
            bitcoin = IconToken("ic_bitcoin", R.drawable.ic_bitcoin),
            cardMembership = IconToken("ic_card_membership", R.drawable.ic_card_membership),
            cardTravel = IconToken("ic_card_travel", R.drawable.ic_card_travel),
            colon = IconToken("ic_colon", R.drawable.ic_colon),
            creditCard = IconToken("ic_credit_card", R.drawable.ic_credit_card),
            creditCardClock = IconToken("ic_credit_card_clock", R.drawable.ic_credit_card_clock),
            creditCardGear = IconToken("ic_credit_card_gear", R.drawable.ic_credit_card_gear),
            creditCardHeart = IconToken("ic_credit_card_heart", R.drawable.ic_credit_card_heart),
            creditCardOff = IconToken("ic_credit_card_off", R.drawable.ic_credit_card_off),
            creditScore = IconToken("ic_credit_score", R.drawable.ic_credit_score),
            dollar = IconToken("ic_dollar", R.drawable.ic_dollar),
            dollarCircle = IconToken("ic_dollar_circle", R.drawable.ic_dollar_circle),
            dollarExchange = IconToken("ic_dollar_exchange", R.drawable.ic_dollar_exchange),
            dollarOff = IconToken("ic_dollar_off", R.drawable.ic_dollar_off),
            euro = IconToken("ic_euro", R.drawable.ic_euro),
            franc = IconToken("ic_franc", R.drawable.ic_franc),
            lira = IconToken("ic_lira", R.drawable.ic_lira),
            moneyBag = IconToken("ic_money_bag", R.drawable.ic_money_bag),
            moneyRange = IconToken("ic_money_range", R.drawable.ic_money_range),
            paymentArrowDown = IconToken("ic_payment_arrow_down", R.drawable.ic_payment_arrow_down),
            paymentCard = IconToken("ic_payment_card", R.drawable.ic_payment_card),
            payments = IconToken("ic_payments", R.drawable.ic_payments),
            pound = IconToken("ic_pound", R.drawable.ic_pound),
            productionQuantityLimits = IconToken("ic_production_quantity_limits", R.drawable.ic_production_quantity_limits),
            psychiatry = IconToken("ic_psychiatry", R.drawable.ic_psychiatry),
            redeem = IconToken("ic_redeem", R.drawable.ic_redeem),
            ruble = IconToken("ic_ruble", R.drawable.ic_ruble),
            rupee = IconToken("ic_rupee", R.drawable.ic_rupee),
            savings = IconToken("ic_savings", R.drawable.ic_savings),
            sendMoney = IconToken("ic_send_money", R.drawable.ic_send_money),
            shoppingBag = IconToken("ic_shopping_bag", R.drawable.ic_shopping_bag),
            shoppingBagSpeed = IconToken("ic_shopping_bag_speed", R.drawable.ic_shopping_bag_speed),
            shoppingCart = IconToken("ic_shopping_cart", R.drawable.ic_shopping_cart),
            shoppingCartCheckout = IconToken("ic_shopping_cart_checkout", R.drawable.ic_shopping_cart_checkout),
            shoppingCartOff = IconToken("ic_shopping_cart_off", R.drawable.ic_shopping_cart_off),
            sprint = IconToken("ic_sprint", R.drawable.ic_sprint),
            toll = IconToken("ic_toll", R.drawable.ic_toll),
            universalCurrency = IconToken("ic_universal_currency", R.drawable.ic_universal_currency),
            universalCurrencyAlt = IconToken("ic_universal_currency_alt", R.drawable.ic_universal_currency_alt),
            wallet = IconToken("ic_wallet", R.drawable.ic_wallet),
            yen = IconToken("ic_yen", R.drawable.ic_yen)

        )

    }
}