package cruxui.android.maracuya.atoms.icons

import cruxui.android.maracuya.R
import cruxui.android.maracuya.tokens.base.IconToken

data class LibraryGeneralIconsTokens (
    // GENERAL ICONS (172)
    val acute: IconToken,
    val add: IconToken,
    val add2: IconToken,
    val addAPhoto: IconToken,
    val addAd: IconToken,
    val addAlert: IconToken,
    val addBox: IconToken,
    val addChatOn: IconToken,
    val addLink: IconToken,
    val addNotes: IconToken,
    val addToPhotos: IconToken,
    val air: IconToken,
    val alarm: IconToken,
    val alarmAdd: IconToken,
    val alarmOff: IconToken,
    val alarmOn: IconToken,
    val alarmSmartWake: IconToken,
    val androidWifi3Bar: IconToken,
    val approvalDelegation: IconToken,
    val approvalDelegationOff: IconToken,
    val arOnYou: IconToken,
    val arStickers: IconToken,
    val archive: IconToken,
    val article: IconToken,
    val articlePerson: IconToken,
    val articleShortcut: IconToken,
    val asterisk: IconToken,
    val attachEmail: IconToken,
    val attachFile: IconToken,
    val attachFileOff: IconToken,
    val attachment: IconToken,
    val autoDelete: IconToken,
    val autoSchedule: IconToken,
    val backHand: IconToken,
    val backlightHigh: IconToken,
    val ballot: IconToken,
    val barChart: IconToken,
    val barChart4Bars: IconToken,
    val bigtopUpdates: IconToken,
    val bluetooth: IconToken,
    val bolt: IconToken,
    val book3: IconToken,
    val book4Spark: IconToken,
    val bookmark: IconToken,
    val bookmarkAdd: IconToken,
    val bookmarkAdded: IconToken,
    val bookmarkHeart: IconToken,
    val bookmarkManager: IconToken,
    val bookmarkStar: IconToken,
    val borderColor: IconToken,
    val build: IconToken,
    val businessCenter: IconToken,
    val calendarAddOn: IconToken,
    val calendarCheck: IconToken,
    val calendarClock: IconToken,
    val calendarLock: IconToken,
    val calendarMonth: IconToken,
    val calendarToday: IconToken,
    val captivePortal: IconToken,
    val cardioLoad: IconToken,
    val celebration: IconToken,
    val chat: IconToken,
    val chatInfo: IconToken,
    val check: IconToken,
    val checkbook: IconToken,
    val checklist: IconToken,
    val cheer: IconToken,
    val chromeReaderMode: IconToken,
    val chromeRestore: IconToken,
    val clarify: IconToken,
    val close: IconToken,
    val construction: IconToken,
    val contactPage: IconToken,
    val contentCopy: IconToken,
    val contentCut: IconToken,
    val contentPaste: IconToken,
    val contentPasteGo: IconToken,
    val contentPasteOff: IconToken,
    val contentPasteSearch: IconToken,
    val contract: IconToken,
    val contractDelete: IconToken,
    val contractEdit: IconToken,
    val createNewFolder: IconToken,
    val dehaze: IconToken,
    val designServices: IconToken,
    val discoverTune: IconToken,
    val distance: IconToken,
    val docs: IconToken,
    val docsAddOn: IconToken,
    val doneAll: IconToken,
    val dragIndicator: IconToken,
    val draw: IconToken,
    val driveFileRenameOutline: IconToken,
    val earthquake: IconToken,
    val eda: IconToken,
    val editCalendar: IconToken,
    val editDocument: IconToken,
    val energyProgramTimeUsed: IconToken,
    val equitSquare: IconToken,
    val factCheck: IconToken,
    val featureSearch: IconToken,
    val fileCopy: IconToken,
    val fileCopyOff: IconToken,
    val fileDownloadDone: IconToken,
    val filterAlt: IconToken,
    val filterNone: IconToken,
    val fingerprint: IconToken,
    val flashOn: IconToken,
    val folder: IconToken,
    val folderCheck2: IconToken,
    val folderMatch: IconToken,
    val folderOff: IconToken,
    val folderShared: IconToken,
    val folderSupervised: IconToken,
    val footprint: IconToken,
    val formatColorReset: IconToken,
    val formatInkHighlighter: IconToken,
    val glucose: IconToken,
    val grade: IconToken,
    val handBones: IconToken,
    val handGesture: IconToken,
    val handGestureOff: IconToken,
    val handshake: IconToken,
    val libraryAddCheck: IconToken,
    val liftToTalk: IconToken,
    val link: IconToken,
    val linkOff: IconToken,
    val lock: IconToken,
    val lookOpen: IconToken,
    val lookOpenRight: IconToken,
    val magicButton: IconToken,
    val manageSearch: IconToken,
    val massage: IconToken,
    val medicalServices: IconToken,
    val minusBar: IconToken,
    val modeHeat: IconToken,
    val modeHeatOff: IconToken,
    val moreTime: IconToken,
    val networkCheck: IconToken,
    val newWindow: IconToken,
    val news: IconToken,
    val newsmode: IconToken,
    val notificationAdd: IconToken,
    val notificationImportant: IconToken,
    val notificationSettings: IconToken,
    val notificationSound: IconToken,
    val notifications: IconToken,
    val notificationsActive: IconToken,
    val notificationsUnread: IconToken,
    val pendingActions: IconToken,
    val permContactCalendar: IconToken,
    val photoCamera: IconToken,
    val soap: IconToken,
    val store: IconToken,
    val swipe: IconToken,
    val swipeDown: IconToken,
    val swipeLeft: IconToken,
    val swipeRight: IconToken,
    val swipeUp: IconToken,
    val swipeVertical: IconToken,
    val tempPreferencesCustom: IconToken,
    val thumbDownOff: IconToken,
    val thumbUp: IconToken,
    val thumbsUpDouble: IconToken,
    val thumbsUpDown: IconToken,
    val touchApp: IconToken,
    val touchDouble: IconToken,
    val touchLong: IconToken,
    val travelExplore: IconToken,
    val visibility: IconToken,
    val visibilityOff: IconToken,
    val wash: IconToken,
    val waterDrop: IconToken,
){
    companion object{
        val general = LibraryGeneralIconsTokens(

            // GENERAL ICONS (172)

            acute = IconToken("ic_acute", R.drawable.ic_acute),
            add = IconToken("ic_add", R.drawable.ic_add),
            add2 = IconToken("ic_add_2", R.drawable.ic_add_2),
            addAPhoto = IconToken("ic_add_a_photo", R.drawable.ic_add_a_photo),
            addAd = IconToken("ic_add_ad", R.drawable.ic_add_ad),
            addAlert = IconToken("ic_add_alert", R.drawable.ic_add_alert),
            addBox = IconToken("ic_add_box", R.drawable.ic_add_box),
            addChatOn = IconToken("ic_add_chat_on", R.drawable.ic_add_chat_on),
            addLink = IconToken("ic_add_link", R.drawable.ic_add_link),
            addNotes = IconToken("ic_add_notes", R.drawable.ic_add_notes),
            addToPhotos = IconToken("ic_add_to_photos", R.drawable.ic_add_to_photos),
            air = IconToken("ic_air", R.drawable.ic_air),
            alarm = IconToken("ic_alarm", R.drawable.ic_alarm),
            alarmAdd = IconToken("ic_alarm_add", R.drawable.ic_alarm_add),
            alarmOff = IconToken("ic_alarm_off", R.drawable.ic_alarm_off),
            alarmOn = IconToken("ic_alarm_on", R.drawable.ic_alarm_on),
            alarmSmartWake = IconToken("ic_alarm_smart_wake", R.drawable.ic_alarm_smart_wake),
            androidWifi3Bar = IconToken("ic_android_wifi_3_bar", R.drawable.ic_android_wifi_3_bar),
            approvalDelegation = IconToken("ic_approval_delegation", R.drawable.ic_approval_delegation),
            approvalDelegationOff = IconToken("ic_approval_delegation_off", R.drawable.ic_approval_delegation_off),
            arOnYou = IconToken("ic_ar_on_you", R.drawable.ic_ar_on_you),
            arStickers = IconToken("ic_ar_stickers", R.drawable.ic_ar_stickers),
            archive = IconToken("ic_archive", R.drawable.ic_archive),
            article = IconToken("ic_article", R.drawable.ic_article),
            articlePerson = IconToken("ic_article_person", R.drawable.ic_article_person),
            articleShortcut = IconToken("ic_article_shortcut", R.drawable.ic_article_shortcut),
            asterisk = IconToken("ic_asterisk", R.drawable.ic_asterisk),
            attachEmail = IconToken("ic_attach_email", R.drawable.ic_attach_email),
            attachFile = IconToken("ic_attach_file", R.drawable.ic_attach_file),
            attachFileOff = IconToken("ic_attach_file_off", R.drawable.ic_attach_file_off),
            attachment = IconToken("ic_attachment", R.drawable.ic_attachment),
            autoDelete = IconToken("ic_auto_delete", R.drawable.ic_auto_delete),
            autoSchedule = IconToken("ic_auto_schedule", R.drawable.ic_auto_schedule),
            backHand = IconToken("ic_back_hand", R.drawable.ic_back_hand),
            backlightHigh = IconToken("ic_backlight_high", R.drawable.ic_backlight_high),
            ballot = IconToken("ic_ballot", R.drawable.ic_ballot),
            barChart = IconToken("ic_bar_chart", R.drawable.ic_bar_chart),
            barChart4Bars = IconToken("ic_bar_chart_4_bars", R.drawable.ic_bar_chart_4_bars),
            bigtopUpdates = IconToken("ic_bigtop_updates", R.drawable.ic_bigtop_updates),
            bluetooth = IconToken("ic_bluetooth", R.drawable.ic_bluetooth),
            bolt = IconToken("ic_bolt", R.drawable.ic_bolt),
            book3 = IconToken("ic_book_3", R.drawable.ic_book_3),
            book4Spark = IconToken("ic_book_4_spark", R.drawable.ic_book_4_spark),
            bookmark = IconToken("ic_bookmark", R.drawable.ic_bookmark),
            bookmarkAdd = IconToken("ic_bookmark_add", R.drawable.ic_bookmark_add),
            bookmarkAdded = IconToken("ic_bookmark_added", R.drawable.ic_bookmark_added),
            bookmarkHeart = IconToken("ic_bookmark_heart", R.drawable.ic_bookmark_heart),
            bookmarkManager = IconToken("ic_bookmark_manager", R.drawable.ic_bookmark_manager),
            bookmarkStar = IconToken("ic_bookmark_star", R.drawable.ic_bookmark_star),
            borderColor = IconToken("ic_border_color", R.drawable.ic_border_color),
            build = IconToken("ic_build", R.drawable.ic_build),
            businessCenter = IconToken("ic_business_center", R.drawable.ic_business_center),
            calendarAddOn = IconToken("ic_calendar_add_on", R.drawable.ic_calendar_add_on),
            calendarCheck = IconToken("ic_calendar_check", R.drawable.ic_calendar_check),
            calendarClock = IconToken("ic_calendar_clock", R.drawable.ic_calendar_clock),
            calendarLock = IconToken("ic_calendar_lock", R.drawable.ic_calendar_lock),
            calendarMonth = IconToken("ic_calendar_month", R.drawable.ic_calendar_month),
            calendarToday = IconToken("ic_calendar_today", R.drawable.ic_calendar_today),
            captivePortal = IconToken("ic_captive_portal", R.drawable.ic_captive_portal),
            cardioLoad = IconToken("ic_cardio_load", R.drawable.ic_cardio_load),
            celebration = IconToken("ic_celebration", R.drawable.ic_celebration),
            chat = IconToken("ic_chat", R.drawable.ic_chat),
            chatInfo = IconToken("ic_chat_info", R.drawable.ic_chat_info),
            check = IconToken("ic_check", R.drawable.ic_check),
            checkbook = IconToken("ic_checkbook", R.drawable.ic_checkbook),
            checklist = IconToken("ic_checklist", R.drawable.ic_checklist),
            cheer = IconToken("ic_cheer", R.drawable.ic_cheer),
            chromeReaderMode = IconToken("ic_chrome_reader_mode", R.drawable.ic_chrome_reader_mode),
            chromeRestore = IconToken("ic_chrome_restore", R.drawable.ic_chrome_restore),
            clarify = IconToken("ic_clarify", R.drawable.ic_clarify),
            close = IconToken("ic_close", R.drawable.ic_close),
            construction = IconToken("ic_construction", R.drawable.ic_construction),
            contactPage = IconToken("ic_contact_page", R.drawable.ic_contact_page),
            contentCopy = IconToken("ic_content_copy", R.drawable.ic_content_copy),
            contentCut = IconToken("ic_content_cut", R.drawable.ic_content_cut),
            contentPaste = IconToken("ic_content_paste", R.drawable.ic_content_paste),
            contentPasteGo = IconToken("ic_content_paste_go", R.drawable.ic_content_paste_go),
            contentPasteOff = IconToken("ic_content_paste_off", R.drawable.ic_content_paste_off),
            contentPasteSearch = IconToken("ic_content_paste_search", R.drawable.ic_content_paste_search),
            contract = IconToken("ic_contract", R.drawable.ic_contract),
            contractDelete = IconToken("ic_contract_delete", R.drawable.ic_contract_delete),
            contractEdit = IconToken("ic_contract_edit", R.drawable.ic_contract_edit),
            createNewFolder = IconToken("ic_create_new_folder", R.drawable.ic_create_new_folder),
            dehaze = IconToken("ic_dehaze", R.drawable.ic_dehaze),
            designServices = IconToken("ic_design_services", R.drawable.ic_design_services),
            discoverTune = IconToken("ic_discover_tune", R.drawable.ic_discover_tune),
            distance = IconToken("ic_distance", R.drawable.ic_distance),
            docs = IconToken("ic_docs", R.drawable.ic_docs),
            docsAddOn = IconToken("ic_docs_add_on", R.drawable.ic_docs_add_on),
            doneAll = IconToken("ic_done_all", R.drawable.ic_done_all),
            dragIndicator = IconToken("ic_drag_indicator", R.drawable.ic_drag_indicator),
            draw = IconToken("ic_draw", R.drawable.ic_draw),
            driveFileRenameOutline = IconToken("ic_drive_file_rename_outline", R.drawable.ic_drive_file_rename_outline),
            earthquake = IconToken("ic_earthquake", R.drawable.ic_earthquake),
            eda = IconToken("ic_eda", R.drawable.ic_eda),
            editCalendar = IconToken("ic_edit_calendar", R.drawable.ic_edit_calendar),
            editDocument = IconToken("ic_edit_document", R.drawable.ic_edit_document),
            energyProgramTimeUsed = IconToken("ic_energy_program_time_used", R.drawable.ic_energy_program_time_used),
            equitSquare = IconToken("ic_equit_square", R.drawable.ic_equit_square),
            factCheck = IconToken("ic_fact_check", R.drawable.ic_fact_check),
            featureSearch = IconToken("ic_feature_search", R.drawable.ic_feature_search),
            fileCopy = IconToken("ic_file_copy", R.drawable.ic_file_copy),
            fileCopyOff = IconToken("ic_file_copy_off", R.drawable.ic_file_copy_off),
            fileDownloadDone = IconToken("ic_file_download_done", R.drawable.ic_file_download_done),
            filterAlt = IconToken("ic_filter_alt", R.drawable.ic_filter_alt),
            filterNone = IconToken("ic_filter_none", R.drawable.ic_filter_none),
            fingerprint = IconToken("ic_fingerprint", R.drawable.ic_fingerprint),
            flashOn = IconToken("ic_flash_on", R.drawable.ic_flash_on),
            folder = IconToken("ic_folder", R.drawable.ic_folder),
            folderCheck2 = IconToken("ic_folder_check_2", R.drawable.ic_folder_check_2),
            folderMatch = IconToken("ic_folder_match", R.drawable.ic_folder_match),
            folderOff = IconToken("ic_folder_off", R.drawable.ic_folder_off),
            folderShared = IconToken("ic_folder_shared", R.drawable.ic_folder_shared),
            folderSupervised = IconToken("ic_folder_supervised", R.drawable.ic_folder_supervised),
            footprint = IconToken("ic_footprint", R.drawable.ic_footprint),
            formatColorReset = IconToken("ic_format_color_reset", R.drawable.ic_format_color_reset),
            formatInkHighlighter = IconToken("ic_format_ink_highlighter", R.drawable.ic_format_ink_highlighter),
            glucose = IconToken("ic_glucose", R.drawable.ic_glucose),
            grade = IconToken("ic_grade", R.drawable.ic_grade),
            handBones = IconToken("ic_hand_bones", R.drawable.ic_hand_bones),
            handGesture = IconToken("ic_hand_gesture", R.drawable.ic_hand_gesture),
            handGestureOff = IconToken("ic_hand_gesture_off", R.drawable.ic_hand_gesture_off),
            handshake = IconToken("ic_handshake", R.drawable.ic_handshake),
            libraryAddCheck = IconToken("ic_library_add_check", R.drawable.ic_library_add_check),
            liftToTalk = IconToken("ic_lift_to_talk", R.drawable.ic_lift_to_talk),
            link = IconToken("ic_link", R.drawable.ic_link),
            linkOff = IconToken("ic_link_off", R.drawable.ic_link_off),
            lock = IconToken("ic_lock", R.drawable.ic_lock),
            lookOpen = IconToken("ic_look_open", R.drawable.ic_look_open),
            lookOpenRight = IconToken("ic_look_open_right", R.drawable.ic_look_open_right),
            magicButton = IconToken("ic_magic_button", R.drawable.ic_magic_button),
            manageSearch = IconToken("ic_manage_search", R.drawable.ic_manage_search),
            massage = IconToken("ic_massage", R.drawable.ic_massage),
            medicalServices = IconToken("ic_medical_services", R.drawable.ic_medical_services),
            minusBar = IconToken("ic_minus_bar", R.drawable.ic_minus_bar),
            modeHeat = IconToken("ic_mode_heat", R.drawable.ic_mode_heat),
            modeHeatOff = IconToken("ic_mode_heat_off", R.drawable.ic_mode_heat_off),
            moreTime = IconToken("ic_more_time", R.drawable.ic_more_time),
            networkCheck = IconToken("ic_network_check", R.drawable.ic_network_check),
            newWindow = IconToken("ic_new_window", R.drawable.ic_new_window),
            news = IconToken("ic_news", R.drawable.ic_news),
            newsmode = IconToken("ic_newsmode", R.drawable.ic_newsmode),
            notificationAdd = IconToken("ic_notification_add", R.drawable.ic_notification_add),
            notificationImportant = IconToken("ic_notification_important", R.drawable.ic_notification_important),
            notificationSettings = IconToken("ic_notification_settings", R.drawable.ic_notification_settings),
            notificationSound = IconToken("ic_notification_sound", R.drawable.ic_notification_sound),
            notifications = IconToken("ic_notifications", R.drawable.ic_notifications),
            notificationsActive = IconToken("ic_notifications_active", R.drawable.ic_notifications_active),
            notificationsUnread = IconToken("ic_notifications_unread", R.drawable.ic_notifications_unread),
            pendingActions = IconToken("ic_pending_actions", R.drawable.ic_pending_actions),
            permContactCalendar = IconToken("ic_perm_contact_calendar", R.drawable.ic_perm_contact_calendar),
            photoCamera = IconToken("ic_photo_camera", R.drawable.ic_photo_camera),
            soap = IconToken("ic_soap", R.drawable.ic_soap),
            store = IconToken("ic_store", R.drawable.ic_store),
            swipe = IconToken("ic_swipe", R.drawable.ic_swipe),
            swipeDown = IconToken("ic_swipe_down", R.drawable.ic_swipe_down),
            swipeLeft = IconToken("ic_swipe_left", R.drawable.ic_swipe_left),
            swipeRight = IconToken("ic_swipe_right", R.drawable.ic_swipe_right),
            swipeUp = IconToken("ic_swipe_up", R.drawable.ic_swipe_up),
            swipeVertical = IconToken("ic_swipe_vertical", R.drawable.ic_swipe_vertical),
            tempPreferencesCustom = IconToken("ic_temp_preferences_custom", R.drawable.ic_temp_preferences_custom),
            thumbDownOff = IconToken("ic_thumb_down_off", R.drawable.ic_thumb_down_off),
            thumbUp = IconToken("ic_thumb_up", R.drawable.ic_thumb_up),
            thumbsUpDouble = IconToken("ic_thumbs_up_double", R.drawable.ic_thumbs_up_double),
            thumbsUpDown = IconToken("ic_thumbs_up_down", R.drawable.ic_thumbs_up_down),
            touchApp = IconToken("ic_touch_app", R.drawable.ic_touch_app),
            touchDouble = IconToken("ic_touch_double", R.drawable.ic_touch_double),
            touchLong = IconToken("ic_touch_long", R.drawable.ic_touch_long),
            travelExplore = IconToken("ic_travel_explore", R.drawable.ic_travel_explore),
            visibility = IconToken("ic_visibility", R.drawable.ic_visibility),
            visibilityOff = IconToken("ic_visibility_off", R.drawable.ic_visibility_off),
            wash = IconToken("ic_wash", R.drawable.ic_wash),
            waterDrop = IconToken("ic_water_drop", R.drawable.ic_water_drop),
        )
    }
}