package com.example.mylibrary.tokens.icons

import com.example.mylibrary.atoms.LibraryIconTokens
import com.example.mylibrary.tokens.base.IconToken

data class AlertsIcons(
    val addCircle: IconToken,
    val addTask: IconToken,
    val adminModerator: IconToken,
    val adminPanelSettings: IconToken,
    val armingCountdown: IconToken,
    val awardStar: IconToken,
    val block: IconToken,
    val cancel: IconToken,
    val checkCircle: IconToken,
    val checkCircleUnread: IconToken,
    val contactSupport: IconToken,
    val crisisAlert: IconToken,
    val emergencyHome: IconToken,
    val encrypted: IconToken,
    val encryptedAddCircle: IconToken,
    val encryptedMinusCircle: IconToken,
    val encryptedOff: IconToken,
    val error: IconToken,
    val gppBad: IconToken,
    val gppMaybe: IconToken,
    val healthAndSafety: IconToken,
    val help: IconToken,
    val highlightKeyboardFocus: IconToken,
    val info: IconToken,
    val lockReset: IconToken,
    val newReleases: IconToken,
    val pending: IconToken,
    val privacyTip: IconToken,
    val settingsAlert: IconToken,
    val starShine: IconToken,
    val warning: IconToken
)

fun getAlertsIcons(atoms: LibraryIconTokens) = AlertsIcons(
    addCircle = atoms.alertsIconsLibrary.addCircle,
    addTask = atoms.alertsIconsLibrary.addTask,
    adminModerator = atoms.alertsIconsLibrary.adminModerator,
    adminPanelSettings = atoms.alertsIconsLibrary.adminPanelSettings,
    armingCountdown = atoms.alertsIconsLibrary.armingCountdown,
    awardStar = atoms.alertsIconsLibrary.awardStar,
    block = atoms.alertsIconsLibrary.block,
    cancel = atoms.alertsIconsLibrary.cancel,
    checkCircle = atoms.alertsIconsLibrary.checkCircle,
    checkCircleUnread = atoms.alertsIconsLibrary.checkCircleUnread,
    contactSupport = atoms.alertsIconsLibrary.contactSupport,
    crisisAlert = atoms.alertsIconsLibrary.crisisAlert,
    emergencyHome = atoms.alertsIconsLibrary.emergencyHome,
    encrypted = atoms.alertsIconsLibrary.encrypted,
    encryptedAddCircle = atoms.alertsIconsLibrary.encryptedAddCircle,
    encryptedMinusCircle = atoms.alertsIconsLibrary.encryptedMinusCircle,
    encryptedOff = atoms.alertsIconsLibrary.encryptedOff,
    error = atoms.alertsIconsLibrary.error,
    gppBad = atoms.alertsIconsLibrary.gppBad,
    gppMaybe = atoms.alertsIconsLibrary.gppMaybe,
    healthAndSafety = atoms.alertsIconsLibrary.healthAndSafety,
    help = atoms.alertsIconsLibrary.help,
    highlightKeyboardFocus = atoms.alertsIconsLibrary.highlightKeyboardFocus,
    info = atoms.alertsIconsLibrary.info,
    lockReset = atoms.alertsIconsLibrary.lockReset,
    newReleases = atoms.alertsIconsLibrary.newReleases,
    pending = atoms.alertsIconsLibrary.pending,
    privacyTip = atoms.alertsIconsLibrary.privacyTip,
    settingsAlert = atoms.alertsIconsLibrary.settingsAlert,
    starShine = atoms.alertsIconsLibrary.starShine,
    warning = atoms.alertsIconsLibrary.warning
)
