package com.example.mylibrary.tokens.icons

import com.example.mylibrary.atoms.LibraryIconTokens
import com.example.mylibrary.tokens.base.IconToken

data class MoneyIcons(
    val accountBalanceWallet: IconToken,
    val addCard: IconToken,
    val addShoppingCart: IconToken,
    val bitcoin: IconToken,
    val cardMembership: IconToken,
    val cardTravel: IconToken,
    val colon: IconToken,
    val creditCard: IconToken,
    val creditCardClock: IconToken,
    val creditCardGear: IconToken,
    val creditCardHeart: IconToken,
    val creditCardOff: IconToken,
    val creditScore: IconToken,
    val dollar: IconToken,
    val dollarCircle: IconToken,
    val dollarExchange: IconToken,
    val dollarOff: IconToken,
    val euro: IconToken,
    val franc: IconToken,
    val lira: IconToken,
    val moneyBag: IconToken,
    val moneyRange: IconToken,
    val paymentArrowDown: IconToken,
    val paymentCard: IconToken,
    val payments: IconToken,
    val pound: IconToken,
    val productionQuantityLimits: IconToken,
    val psychiatry: IconToken,
    val redeem: IconToken,
    val ruble: IconToken,
    val rupee: IconToken,
    val savings: IconToken,
    val sendMoney: IconToken,
    val shoppingBag: IconToken,
    val shoppingBagSpeed: IconToken,
    val shoppingCart: IconToken,
    val shoppingCartCheckout: IconToken,
    val shoppingCartOff: IconToken,
    val sprint: IconToken,
    val toll: IconToken,
    val universalCurrency: IconToken,
    val universalCurrencyAlt: IconToken,
    val wallet: IconToken,
    val yen: IconToken
)

fun getMoneyIcons(atoms: LibraryIconTokens) = MoneyIcons(
    accountBalanceWallet = atoms.moneyIconsLibrary.accountBalanceWallet,
    addCard = atoms.moneyIconsLibrary.addCard,
    addShoppingCart = atoms.moneyIconsLibrary.addShoppingCart,
    bitcoin = atoms.moneyIconsLibrary.bitcoin,
    cardMembership = atoms.moneyIconsLibrary.cardMembership,
    cardTravel = atoms.moneyIconsLibrary.cardTravel,
    colon = atoms.moneyIconsLibrary.colon,
    creditCard = atoms.moneyIconsLibrary.creditCard,
    creditCardClock = atoms.moneyIconsLibrary.creditCardClock,
    creditCardGear = atoms.moneyIconsLibrary.creditCardGear,
    creditCardHeart = atoms.moneyIconsLibrary.creditCardHeart,
    creditCardOff = atoms.moneyIconsLibrary.creditCardOff,
    creditScore = atoms.moneyIconsLibrary.creditScore,
    dollar = atoms.moneyIconsLibrary.dollar,
    dollarCircle = atoms.moneyIconsLibrary.dollarCircle,
    dollarExchange = atoms.moneyIconsLibrary.dollarExchange,
    dollarOff = atoms.moneyIconsLibrary.dollarOff,
    euro = atoms.moneyIconsLibrary.euro,
    franc = atoms.moneyIconsLibrary.franc,
    lira = atoms.moneyIconsLibrary.lira,
    moneyBag = atoms.moneyIconsLibrary.moneyBag,
    moneyRange = atoms.moneyIconsLibrary.moneyRange,
    paymentArrowDown = atoms.moneyIconsLibrary.paymentArrowDown,
    paymentCard = atoms.moneyIconsLibrary.paymentCard,
    payments = atoms.moneyIconsLibrary.payments,
    pound = atoms.moneyIconsLibrary.pound,
    productionQuantityLimits = atoms.moneyIconsLibrary.productionQuantityLimits,
    psychiatry = atoms.moneyIconsLibrary.psychiatry,
    redeem = atoms.moneyIconsLibrary.redeem,
    ruble = atoms.moneyIconsLibrary.ruble,
    rupee = atoms.moneyIconsLibrary.rupee,
    savings = atoms.moneyIconsLibrary.savings,
    sendMoney = atoms.moneyIconsLibrary.sendMoney,
    shoppingBag = atoms.moneyIconsLibrary.shoppingBag,
    shoppingBagSpeed = atoms.moneyIconsLibrary.shoppingBagSpeed,
    shoppingCart = atoms.moneyIconsLibrary.shoppingCart,
    shoppingCartCheckout = atoms.moneyIconsLibrary.shoppingCartCheckout,
    shoppingCartOff = atoms.moneyIconsLibrary.shoppingCartOff,
    sprint = atoms.moneyIconsLibrary.sprint,
    toll = atoms.moneyIconsLibrary.toll,
    universalCurrency = atoms.moneyIconsLibrary.universalCurrency,
    universalCurrencyAlt = atoms.moneyIconsLibrary.universalCurrencyAlt,
    wallet = atoms.moneyIconsLibrary.wallet,
    yen = atoms.moneyIconsLibrary.yen
)