package com.example.mylibrary.atoms.icons

import com.example.mylibrary.R
import com.example.mylibrary.tokens.base.IconToken

data class LibraryArrowIconsTokens (

    //ARROW ICONS (65)
    val adsClick: IconToken,
    val arrowCircleDown: IconToken,
    val arrowCircleLeft: IconToken,
    val arrowCircleRight: IconToken,
    val arrowCircleUp: IconToken,
    val arrowDropDown: IconToken,
    val arrowDropUp: IconToken,
    val arrowLeft: IconToken,
    val arrowOrEdge: IconToken,
    val arrowRangeHoriz: IconToken,
    val arrowRangeVert: IconToken,
    val arrowRight: IconToken,
    val arrowSelectorTool: IconToken,
    val arrowSplit: IconToken,
    val arrowsInput: IconToken,
    val arrowsMoreDownLeft: IconToken,
    val arrowsMoreDownRight: IconToken,
    val arrowsMoreUpLeft: IconToken,
    val arrowsMoreUpRight: IconToken,
    val arrowsOutput: IconToken,
    val arrowsOutwardHoriz: IconToken,
    val arrowsOutwardVert: IconToken,
    val closeFullscreen: IconToken,
    val code: IconToken,
    val download: IconToken,
    val dragClick: IconToken,
    val expandAll: IconToken,
    val expandCircleDown: IconToken,
    val expandCircleLeft: IconToken,
    val expandCircleRight: IconToken,
    val expandCircleUp: IconToken,
    val expandLess: IconToken,
    val expandMore: IconToken,
    val forwardMedia: IconToken,
    val input: IconToken,
    val keyboardArrowLeft: IconToken,
    val keyboardArrowRight: IconToken,
    val keyboardBackspaceDown: IconToken,
    val keyboardBackspaceLeft: IconToken,
    val keyboardBackspaceRight: IconToken,
    val keyboardBackspaceUp: IconToken,
    val keyboardDoubleArrowDown: IconToken,
    val keyboardDoubleArrowUp: IconToken,
    val keyboardTabDown: IconToken,
    val keyboardTabLeft: IconToken,
    val keyboardTabRight: IconToken,
    val keyboardTabUp: IconToken,
    val login: IconToken,
    val logout: IconToken,
    val navigateBefore: IconToken,
    val navigateNext: IconToken,
    val openInFull: IconToken,
    val openInNew: IconToken,
    val openInNewDown: IconToken,
    val openInNewOff: IconToken,
    val openRun: IconToken,
    val openWith: IconToken,
    val output: IconToken,
    val repeat: IconToken,
    val swapHoriz: IconToken,
    val swapVert: IconToken,
    val sync: IconToken,
    val syncDisabled: IconToken,
    val trendingUp: IconToken,
    val upload: IconToken,
){
    companion object{
        val arrows = LibraryArrowIconsTokens(
            //ARROW ICONS (65)
            adsClick = IconToken("ic_ads_click", R.drawable.ic_ads_click),
            arrowCircleDown = IconToken("ic_arrow_circle_down", R.drawable.ic_arrow_circle_down),
            arrowCircleLeft = IconToken("ic_arrow_circle_left", R.drawable.ic_arrow_circle_left),
            arrowCircleRight = IconToken("ic_arrow_circle_right", R.drawable.ic_arrow_circle_right),
            arrowCircleUp = IconToken("ic_arrow_circle_up", R.drawable.ic_arrow_circle_up),
            arrowDropDown = IconToken("ic_arrow_drop_down", R.drawable.ic_arrow_drop_down),
            arrowDropUp = IconToken("ic_arrow_drop_up", R.drawable.ic_arrow_drop_up),
            arrowLeft = IconToken("ic_arrow_left", R.drawable.ic_arrow_left),
            arrowOrEdge = IconToken("ic_arrow_or_edge", R.drawable.ic_arrow_or_edge),
            arrowRangeHoriz = IconToken("ic_arrow_range_horiz", R.drawable.ic_arrow_range_horiz),
            arrowRangeVert = IconToken("ic_arrow_range_vert", R.drawable.ic_arrow_range_vert),
            arrowRight = IconToken("ic_arrow_right", R.drawable.ic_arrow_right),
            arrowSelectorTool = IconToken("ic_arrow_selector_tool", R.drawable.ic_arrow_selector_tool),
            arrowSplit = IconToken("ic_arrow_split", R.drawable.ic_arrow_split),
            arrowsInput = IconToken("ic_arrows_input", R.drawable.ic_arrows_input),
            arrowsMoreDownLeft = IconToken("ic_arrows_more_down_left", R.drawable.ic_arrows_more_down_left),
            arrowsMoreDownRight = IconToken("ic_arrows_more_down_right", R.drawable.ic_arrows_more_down_right),
            arrowsMoreUpLeft = IconToken("ic_arrows_more_up_left", R.drawable.ic_arrows_more_up_left),
            arrowsMoreUpRight = IconToken("ic_arrows_more_up_right", R.drawable.ic_arrows_more_up_right),
            arrowsOutput = IconToken("ic_arrows_output", R.drawable.ic_arrows_output),
            arrowsOutwardHoriz = IconToken("ic_arrows_outward_horiz", R.drawable.ic_arrows_outward_horiz),
            arrowsOutwardVert = IconToken("ic_arrows_outward_vert", R.drawable.ic_arrows_outward_vert),
            closeFullscreen = IconToken("ic_close_fullscreen", R.drawable.ic_close_fullscreen),
            code = IconToken("ic_code", R.drawable.ic_code),
            download = IconToken("ic_download", R.drawable.ic_download),
            dragClick = IconToken("ic_drag_click", R.drawable.ic_drag_click),
            expandAll = IconToken("ic_expand_all", R.drawable.ic_expand_all),
            expandCircleDown = IconToken("ic_expand_circle_down", R.drawable.ic_expand_circle_down),
            expandCircleLeft = IconToken("ic_expand_circle_left", R.drawable.ic_expand_circle_left),
            expandCircleRight = IconToken("ic_expand_circle_right", R.drawable.ic_expand_circle_right),
            expandCircleUp = IconToken("ic_expand_circle_up", R.drawable.ic_expand_circle_up),
            expandLess = IconToken("ic_expand_less", R.drawable.ic_expand_less),
            expandMore = IconToken("ic_expand_more", R.drawable.ic_expand_more),
            forwardMedia = IconToken("ic_forward_media", R.drawable.ic_forward_media),
            input = IconToken("ic_input", R.drawable.ic_input),
            keyboardArrowLeft = IconToken("ic_keyboard_arrow_left", R.drawable.ic_keyboard_arrow_left),
            keyboardArrowRight = IconToken("ic_keyboard_arrow_right", R.drawable.ic_keyboard_arrow_right),
            keyboardBackspaceDown = IconToken("ic_keyboard_backspace_down", R.drawable.ic_keyboard_backspace_down),
            keyboardBackspaceLeft = IconToken("ic_keyboard_backspace_left", R.drawable.ic_keyboard_backspace_left),
            keyboardBackspaceRight = IconToken("ic_keyboard_backspace_right", R.drawable.ic_keyboard_backspace_right),
            keyboardBackspaceUp = IconToken("ic_keyboard_backspace_up", R.drawable.ic_keyboard_backspace_up),
            keyboardDoubleArrowDown = IconToken("ic_keyboard_double_arrow_down", R.drawable.ic_keyboard_double_arrow_down),
            keyboardDoubleArrowUp = IconToken("ic_keyboard_double_arrow_up", R.drawable.ic_keyboard_double_arrow_up),
            keyboardTabDown = IconToken("ic_keyboard_tab_down", R.drawable.ic_keyboard_tab_down),
            keyboardTabLeft = IconToken("ic_keyboard_tab_left", R.drawable.ic_keyboard_tab_left),
            keyboardTabRight = IconToken("ic_keyboard_tab_right", R.drawable.ic_keyboard_tab_right),
            keyboardTabUp = IconToken("ic_keyboard_tab_up", R.drawable.ic_keyboard_tab_up),
            login = IconToken("ic_login", R.drawable.ic_login),
            logout = IconToken("ic_logout", R.drawable.ic_logout),
            navigateBefore = IconToken("ic_navigate_before", R.drawable.ic_navigate_before),
            navigateNext = IconToken("ic_navigate_next", R.drawable.ic_navigate_next),
            openInFull = IconToken("ic_open_in_full", R.drawable.ic_open_in_full),
            openInNew = IconToken("ic_open_in_new", R.drawable.ic_open_in_new),
            openInNewDown = IconToken("ic_open_in_new_down", R.drawable.ic_open_in_new_down),
            openInNewOff = IconToken("ic_open_in_new_off", R.drawable.ic_open_in_new_off),
            openRun = IconToken("ic_open_run", R.drawable.ic_open_run),
            openWith = IconToken("ic_open_with", R.drawable.ic_open_with),
            output = IconToken("ic_output", R.drawable.ic_output),
            repeat = IconToken("ic_repeat", R.drawable.ic_repeat),
            swapHoriz = IconToken("ic_swap_horiz", R.drawable.ic_swap_horiz),
            swapVert = IconToken("ic_swap_vert", R.drawable.ic_swap_vert),
            sync = IconToken("ic_sync", R.drawable.ic_sync),
            syncDisabled = IconToken("ic_sync_disabled", R.drawable.ic_sync_disabled),
            trendingUp = IconToken("ic_trending_up", R.drawable.ic_trending_up),
            upload = IconToken("ic_upload", R.drawable.ic_upload),

        )

    }
}